server:
  port: 8888
spring:
  application:
    name: gateway

# 网关配置
# routes.auth.path: 认证服务：响应的路径
# routes.auth.sensitiveHeaders: 敏感头信息
# routes.auth.serviceId: 重定向到的服务（根据服务id到注册中心获取服务地址）
# routes.producer.path: 生产者服务：相应的路径
# routes.producer.sensitiveHeaders: 敏感头信息
# routes.producer.serviceId:  重定向到的服务（根据服务id到注册中心获取服务地址）
# add-proxy-headers: 添加代理头
zuul:
  routes:
    auth:
      path: /sso/auth/**
      sensitiveHeaders:
      serviceId: sso
    producer:
      path: /api/**
      sensitiveHeaders:
      serviceId: service-api
  add-proxy-headers: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/